# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZjQxZTViNGRiMWYyODFmZWY1NzU1ZTkzNDkyZTIwNGFhNDA1NjRhYzhkZTA3ZjI2ZDk2N2FhZmQ4MTMxYjc2MTc4NDBmOTZhNjk0ZGE1ZDczYjY4YmQ5ZTYwNDU2MGViYjkzZTJmOTc1YjYyYTRiZjU1Yjg0YTYxNGViYjNmMzE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
